/* Copyright © 2020 VMware, Inc. All Rights Reserved.
  SPDX-License-Identifier: BSD-2-Clause
 *
 * API version: 3.2.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)*/

package administration

// Node Health information
type NodeHealth struct {
	// Flag indicating that node is healthy or not
	Healthy bool `json:"healthy,omitempty"`
	// Components health details
	ComponentsHealth string `json:"components_health,omitempty"`
}
